In [1]:
# Import tf
import tensorflow as tf
import numpy as np
from array import array

In [2]:
r1 = tf.constant(1, tf.int16)

In [3]:
print(r1)

tf.Tensor(1, shape=(), dtype=int16)


In [4]:
r2 = tf.constant(1, tf.int16, name = "my_scalar")

In [5]:
print(r2)

tf.Tensor(1, shape=(), dtype=int16)


In [6]:
r1_decimal = tf.constant(1.234,tf.float32)
print(r1_decimal)

tf.Tensor(1.234, shape=(), dtype=float32)


In [7]:
# Decimal
r1_decimal = tf.constant(1.12345, tf.float32)
print(r1_decimal)
# String
r1_string = tf.constant("Guru99", tf.string)
print(r1_string)

tf.Tensor(1.12345, shape=(), dtype=float32)
tf.Tensor(b'Guru99', shape=(), dtype=string)


In [8]:
## Rank 2
r2_matrix = tf.constant([ [1, 2],
                          [3, 4] ],tf.int16)
print(r2_matrix)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int16)


In [9]:
r3_matrix = tf.constant([ [[1, 2],
                           [3, 4], 
                           [5, 6]] ], tf.int16)
print(r3_matrix)

tf.Tensor(
[[[1 2]
  [3 4]
  [5 6]]], shape=(1, 3, 2), dtype=int16)


In [10]:
print(tf.zeros(10))

tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(10,), dtype=float32)


In [11]:
tf.constant(12, tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=12.0>

In [12]:
tf.zeros(10)

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>

In [13]:
tf.ones([10,10])

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [14]:
tf.ones([10,10],dtype=tf.float32,name="sample")

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [15]:
m_shape = tf.constant([ [10, 11],
                        [12, 13],
                        [14, 15] ]                      
                     )

In [16]:
m_shape.shape


TensorShape([3, 2])

In [17]:
m_shape.shape[0]

3

In [18]:
print(m_shape.dtype)

<dtype: 'int32'>


In [19]:
type_float = tf.constant(3.12344,tf.float32)
type_int = tf.cast(type_float,dtype=tf.int32)
print(type_float.dtype)
print(type_int.dtype)

<dtype: 'float32'>
<dtype: 'int32'>


In [20]:
x= tf.constant([2.0],dtype=tf.float32)
print(tf.sqrt(x))

tf.Tensor([1.4142135], shape=(1,), dtype=float32)


In [21]:
print(tf.add(3,5))

tf.Tensor(8, shape=(), dtype=int32)


In [22]:
print(tf.exp(2.4))

tf.Tensor(11.023177, shape=(), dtype=float32)


In [23]:
var1 = tf.Variable(3.,dtype=tf.float64)
print(var1.name)
var2 = tf.Variable(var1,dtype=tf.float64)
print(var2)

Variable:0
<tf.Variable 'Variable:0' shape=() dtype=float64, numpy=3.0>


In [3]:
m1 = [[1.0,2.0],[3.5,3.5]]

In [8]:
m2 = np.array([[1.0, 2.0],
[3.0, 4.0]], dtype=np.float32)

In [3]:
m3 = tf.constant([[2.0,2.0],[3.0,4.5]])


In [11]:
print(type(m1))
print(type(m2))
print(type(m3))

<class 'list'>
<class 'numpy.ndarray'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [12]:
t1 = tf.convert_to_tensor(m1,dtype=tf.float32)
t2 = tf.convert_to_tensor(m2,dtype=tf.float32)
t3 =tf.convert_to_tensor(m3,dtype=tf.float32)

In [13]:
print(type(t1))
print(type(t2))
print(type(t3))

<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [14]:
constm1 = tf.constant([[1.,2.]])
print(constm1)

tf.Tensor([[1. 2.]], shape=(1, 2), dtype=float32)


In [15]:
print(tf.constant([[[1,2],[3,4],[5,6],[9,10]]]))

tf.Tensor(
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 9 10]]], shape=(1, 4, 2), dtype=int32)
